name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  
jobs:
  update_submodule:
    runs-on: macos-latest
    steps:

      - name: Install Postgres
        run: brew install postgresql

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Make sure to check out the sub-module

      - name: Update submodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: Check if changes were made
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes were made."
          else
            echo "Changes were made."
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions - update submodules"
            git add .
            git commit -m 'Update submodule'
            git push
          fi
          
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
      # - name: Test
      #   working-directory: ${{github.workspace}}/build
      #   run: ctest -C ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install build

      - name: Extract version from CMakeLists.txt
        id: version
        run: |
          VERSION=$(sed -nE 's/^project\([^)]*VERSION[[:space:]]+([0-9]+\.[0-9]+\.[0-9]+).*/\1/p' CMakeLists.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload install artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mosaify-${{ steps.version.outputs.version }}
          path: ${{github.workspace}}/build/

        
